<a href="https://colab.research.google.com/github/VAEH/curso-python/blob/master/8_concat_append.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Concatenación de DataFrames: concat y append

Concatenación de dos dataFrames

In [1]:
!pip install --upgrade pandas

     |████████████████████████████████| 9.9MB 5.2MB/s 
ERROR: google-colab 1.0.0 has requirement pandas~=1.1.0; python_version >= "3.0", but you'll have pandas 1.2.4 which is incompatible.
  Found existing installation: pandas 1.1.5
    Uninstalling pandas-1.1.5:
      Successfully uninstalled pandas-1.1.5


In [1]:
import pandas as pd
import numpy as np
pd.__version__

'1.2.4'

Este comando se usa para que los números que vamos a mostrar en el proceso, solo tengan dos cifras decimales. 

In [2]:
pd.options.display.float_format = '{:.2f}'.format

En la librería Numpy se puede hacer lo mismo. 

In [3]:
np.set_printoptions(precision=1)

Generamos números aleatorios con Numpy. Calculamos para una matriz de 2x5

In [8]:
x1 = np.random.rand(2,5)*10
x1

array([[4.8, 0.6, 6.3, 8.7, 2.6],
       [9. , 7. , 6.2, 2. , 3.1]])

Esta vez calculamos para números negativos, que nos va a permitir identificar cuando vamos a concatenar. 

In [6]:
x2 = np.random.rand(2,5)*-1
x2

array([[-0.6, -0.4, -0.7, -0.3, -0.2],
       [-0.6, -0.2, -0.7, -0.1, -0.1]])

`Numpy` puede concatenar matrices usando la función `concatenate([])`, en una lista de objetos, se oolocan las dos matrices.

La primer parte 'X1', se ha puesto en la parte de encima y 'X2' en la parte de abajo, quedan concatenados. 

In [9]:
np.concatenate([x1,x2])

array([[ 4.8,  0.6,  6.3,  8.7,  2.6],
       [ 9. ,  7. ,  6.2,  2. ,  3.1],
       [-0.6, -0.4, -0.7, -0.3, -0.2],
       [-0.6, -0.2, -0.7, -0.1, -0.1]])

vemos las dimensiones. 

In [ ]:
np.concatenate([x1,x2]).shape

(4, 5)

Se puede concatenar en el eje de las columnas, esto se hace especificando el eje a traves de `axis=1`

In [10]:
np.concatenate([x1,x2], axis = 1)

array([[ 4.8,  0.6,  6.3,  8.7,  2.6, -0.6, -0.4, -0.7, -0.3, -0.2],
       [ 9. ,  7. ,  6.2,  2. ,  3.1, -0.6, -0.2, -0.7, -0.1, -0.1]])

vemos dimensiones. 

In [ ]:
np.concatenate([x1,x2], axis = 1).shape

(2, 10)

Ahora se ve la concatenación con **Pandas**. Usamos `.series()` cogemos la primer fila y definimos los indices del elemento.  

In [11]:
s1 = pd.Series(x1[0],index = ['a','b','c','d','e'])
s1

a   4.82
b   0.60
c   6.35
d   8.71
e   2.55
dtype: float64

Tomamos los otros y se hace lo mismo. 

In [ ]:
s2 = pd.Series(x2[0],index = ['c','d','e','f','g'])
s2

c   -0.34
d   -0.73
e   -0.38
f   -0.54
g   -0.04
dtype: float64

Para hacer una concatenación en Pandas, usamos `.concat()` se coloca la lista de las series que queremos concatenar. usamos `axis=1` para alterar el comportamiento y que la concatenacón se haga al lado de la columna y no de bajo.  

Se concatenaron a los largo de las columnas. Se tiene en cuenta que cuando se concatena, se respeta los indices a los que pertenece. 

In [ ]:
pd.concat([s1,s2], axis=1)

0     1
a 6.44   nan
b 0.10   nan
c 2.05 -0.34
d 8.71 -0.73
e 5.20 -0.38
f  nan -0.54
g  nan -0.04

Sí el objetivo es concatenar dos series a lo largo del eje de las columnas, sin respectar el indice, lo que podemos hacer es simplemente resetear su indice, esto se hace a traves del comando `.reset_index()`, el cual borra el indice previamente definido. Para que no siga apareciendo como columna se puede ingresra el parametro `drop=True`

In [ ]:
s1.reset_index(drop=True)

0   6.44
1   0.10
2   2.05
3   8.71
4   5.20
dtype: float64

Se concatena las dos series definidas previamente, pero está vez ya no respeta el indice, bueno, se continua respetando pero sin embargo, se respeta el nuevo indice que se ha creado con `reset_index()`

In [ ]:
pd.concat([s1.reset_index(drop=True),s2.reset_index(drop=True)], axis=1)

0     1
0 6.44 -0.34
1 0.10 -0.73
2 2.05 -0.38
3 8.71 -0.54
4 5.20 -0.04

### Concatenación de DataFrames

Se crea la matriz de 3x2 con números entre 0 y 3, cuyas columnas son 'a' y 'b' 

In [12]:
df1 = pd.DataFrame(np.random.rand(3,2)*10,columns=['a','b'])
df1

a    b
0 5.67 1.69
1 3.93 2.45
2 0.68 2.99

In [13]:
#Decimos que sus indices sean: 2,3,4
df2 = pd.DataFrame(np.random.rand(3,2)*-1,columns=['a','b'], index = [2,3,4])
df2

a     b
2 -0.52 -0.05
3 -0.83 -0.25
4 -0.31 -0.50

Usamoa `.concat([])` para concatenar los dos dataframes 

In [ ]:
pd.concat([df1,df2])
#Vemos que se repide el indice 2

a     b
0  1.29  5.86
1  7.82  1.88
2  8.89  9.38
2 -0.22 -0.92
3 -0.59 -0.36
4 -0.13 -0.91

Concatenación a lo largo de las columnas, especificamos el eje con el parametro `axis=1`

In [ ]:
pd.concat([df1,df2], axis=1)

a    b     a     b
0 1.29 5.86   nan   nan
1 7.82 1.88   nan   nan
2 8.89 9.38 -0.22 -0.92
3  nan  nan -0.59 -0.36
4  nan  nan -0.13 -0.91

Si hacemos la concatenación de dos dataframes, y se quiere hacer enfasis en la columna que se comparten, lo podemos hacer atraves del argumento`join='inner'`.

Obtenemos la fila donde los dos dataframes comparten el indice. 

In [ ]:
pd.concat([df1,df2], axis=1, join='inner')

a    b     a     b
2 8.89 9.38 -0.22 -0.92

Si no se quiere respectar suus indices, se hace de la siguiente forma, reseteando sus indices previamente `.reset_index(drop=True)`

In [ ]:
pd.concat([
           df1.reset_index(drop=True),
           df2.reset_index(drop=True)
           ], axis=1)

a    b     a     b
0 1.29 5.86 -0.22 -0.92
1 7.82 1.88 -0.59 -0.36
2 8.89 9.38 -0.13 -0.91

 Hay una forma más simple de concatenar dataFrames y es con la función `.append()`, lo que va hacer es que la segunda matriz se va a pegar debajo de la primera. Se puede hacer `.append()` de multiples dataframes

In [ ]:
df1.append(df2).append(df2)

a     b
0  1.29  5.86
1  7.82  1.88
2  8.89  9.38
2 -0.22 -0.92
3 -0.59 -0.36
4 -0.13 -0.91
2 -0.22 -0.92
3 -0.59 -0.36
4 -0.13 -0.91

`.append` a lo largo de las columnas, se debe usar lo que se conoce como la traspuesta de nuestro dataFrame `.T` la traspuesta es simplemente invertir donde están las columnas por filas, y donde están las filas por columnas.  

In [ ]:
df1.T

0    1    2
a 1.29 7.82 8.89
b 5.86 1.88 9.38

Se usa `.append()` sobre la traspuesta y sobre esas dos, la traspuesta. Con esto se logra añadir la matriz a lo largo de las columnas. 

In [ ]:
df1.T.append(df2.T).T

a    b     a     b
0 1.29 5.86   nan   nan
1 7.82 1.88   nan   nan
2 8.89 9.38 -0.22 -0.92
3  nan  nan -0.59 -0.36
4  nan  nan -0.13 -0.91

Una funcionalidad extra de pandas que puede ser útil es pd.update().
Donde básicamente si tengo df1 y df2, al hacer pdf1.update(df2) me actualiza o cambia los valores de df1 tomando los de df2 , pero sólo de las columnas que tienen en común.